ASAA

diff --git a/.github/workflows/failure-expre-jobs.yml b/.github/workflows/failure-expre-jobs.yml
--- a/.github/workflows/failure-expre-jobs.yml
+++ b/.github/workflows/failure-expre-jobs.yml
@@ -7,9 +7,18 @@ jobs:
     runs-on: ubuntu-latest
     allow-failure: true
     steps:
+      - id: build
       - name: Fail intentionally
-        run: exit 1  # Simulating failure
+        strategy:
+        matrix:
+        code: [1]
+        run: exit ${{ matrix.code }} # Simulating failure
         continue-on-error: true
+      - uses: mainmatter/continue-on-error-comment@v1
+        with:
+          repo-token: ${{ secrets.GITHUB_TOKEN }}
+          outcome: ${{ steps.build.outcome }}
+          test-id: Error code ${{ matrix.code }}
 
   run-on-failure:
     runs-on: ubuntu-latest
