another job

diff --git a/.github/workflows/failure-expre-jobs.yml b/.github/workflows/failure-expre-jobs.yml
--- a/.github/workflows/failure-expre-jobs.yml
+++ b/.github/workflows/failure-expre-jobs.yml
@@ -1,20 +1,18 @@
-name: Failure expresion
+name: Job Runs on Failure
 
-on: [push, pull_request]
+on: [push]
 
 jobs:
-  job1:
+  main-job:
     runs-on: ubuntu-latest
-    continue-on-error: true
     steps:
-      - name: JobA fail
-        run: exit 1
-        continue-on-error: true
+      - name: Fail intentionally
+        run: exit 1  # Simulating failure
 
-  job2:
+  run-on-failure:
     runs-on: ubuntu-latest
-    needs: job1
+    needs: main-job  # Runs after main-job
+    if: failure()  # Only runs if main-job fails
     steps:
-      - name: Job con dependencia
-        if: ${{ failure() }}
-        run: echo 'Fallo el job1'
+      - name: Notify on failure
+        run: echo "Previous job failed! Running recovery actions..."
