asdasf

diff --git a/.github/workflows/failure-expre-jobs.yml b/.github/workflows/failure-expre-jobs.yml
--- a/.github/workflows/failure-expre-jobs.yml
+++ b/.github/workflows/failure-expre-jobs.yml
@@ -8,21 +8,17 @@ jobs:
     continue-on-error: true
     
     steps:
-      - name: primer job
-        run: echo 'primer job'
-        
       - name: JobA fail
-        run: exit 1
+        run: |
+          echo 'exit error'
+          exit 1
 
   job2:
     runs-on: ubuntu-latest
     needs: job1
     
     steps:
-      - name: segundo job
-        run: echo 'segundo job'
-    
       - name: Job con dependencia
-        run: echo 'fallo'
-        #if: failure()
-        #run: echo 'Fallo el job1'
+        run: echo 'Fallo el job1'
+        if: failure()
+        run: echo 'Fallo el job1'
